version: "3.8"
services:
  postgres:
    image: "postgres:latest"
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jan.bancarewicz
      POSTGRES_PASSWORD: 1qaz2wsx#EDC
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: jan.bancarewicz@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1qaz2wsx#EDC
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data: