const colorMap = {
    // '1': 'Aqua',
    '69': 'Dark Tan',
    '11': 'Black',
    // '3': 'Brick Yellow',
    '7': 'Bright Blue',
    // '1': 'Bright Bluish Green',
    '6': 'Bright Green',
    '4': 'Bright Orange',
    // '1': 'Bright Purple',
    '5': 'Bright Red',
    // '1': 'Bright Reddish Violet',
    '3': 'Bright Yellow',
    // '1': 'Bright Yellowish Green',
    // '1': 'Cool Yellow',
    // '1': 'Dark Azur',
    '120': 'Dark Brown',
    '8': 'Brown',
    // '1': 'Dark Green',
    '68': 'Dark Orange',
    '85': 'Dark Stone Grey',
    '63': 'Earth Blue',
    // '1': 'Earth Green',
    // '1': 'Flame Yellowish Orange',
    // '1': 'Light Purple',
    // '1': 'Light Royal Blue',
    // '1': 'Medium Azur',
    '42': 'Medium Blue',
    // '1': 'Medium Lavender',
    // '1': 'Medium Lilac',
    // '1': 'Medium Nougat',
    '86': 'Medium Stone Grey',
    '59': 'Dark Red',
    // '1': 'Olive Green',
    '88': 'Reddish Brown',
    // '1': 'Sand Green',
    '2': 'Sand Yellow',
    '77': 'Silver Metallic',
    '95': 'Silver',
    // '1': 'Spring Yellowish Green',
    '14': 'Tr. Blue',
    // '1': 'Tr. Bright Green',
    '18': 'Tr. Bright Orange',
    // '1': 'Tr. Brown',
    '20': 'Tr. Green',
    '15': 'Tr. Light Blue',
    // '1': 'Tr. Medium Reddish Violet',
    '17': 'Tr. Red',
    '19': 'Tr. Yellow',
    // '1': 'Transparent',
    // '1': 'Vibrant Coral',
    // '1': 'Warm Gold',
    '1': 'White',
    '21': 'Chrome Gold',
    '98': 'Trans-Orange',
    '99': 'Very Light Bluish Gray',
    '115': 'Pearl Gold',
    '0': 'Plastic Flag',
    '66': 'Metallic Dark Grey',
    '999': "uknow",
    'pi116.jpg': 'pirate pi116',
    'pi121.jpg': 'pirate pi121',
    'pi117.jpg': 'pirate pi117',
    'pi119.jpg': 'pirate pi119',
    'pi098.jpg': 'pirate pi098',
    'pi087.jpg': 'pirate pi087',
    'pi118.jpg': 'pirate pi118',
    'pi090.jpg': 'pirate pi090',
    'pi120.jpg': 'pirate pi120'
};

module.exports = colorMap;